version: '3.1'

services:
  webapp:
    build:
      context: ../../.
      dockerfile: ./examples/ttl/Dockerfile
    image: villemontreal/express-idempotency-mongo-adapter-example
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.14
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
